version: "3"

services:

  scylla-node1:
    image: scylladb/scylla:4.2.4
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "node1-data:/var/lib/scylla/data"
      - "node1-commitlog:/var/lib/scylla/commitlog"
    ports:
      - "9042:9042"
    networks:
      web:

  scylla-node2:
    image: scylladb/scylla:4.2.4
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "node2-data:/var/lib/scylla/data"
      - "node2-commitlog:/var/lib/scylla/commitlog"
    ports:
      - "9043:9042"
    networks:
      web:

  scylla-node3:
    image: scylladb/scylla:4.2.4
    restart: always
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    volumes:
      - "./scylla/scylla.yaml:/etc/scylla/scylla.yaml"
      - "./scylla/cassandra-rackdc.properties.dc1:/etc/scylla/cassandra-rackdc.properties"
      - "node3-data:/var/lib/scylla/data"
      - "node3-commitlog:/var/lib/scylla/commitlog"
    ports:
      - "9044:9042"
    networks:
      web:

networks:
  web:
    driver: bridge

volumes:
  node1-data:
  node1-commitlog:
  node2-data:
  node2-commitlog:
  node3-data:
  node3-commitlog:
